name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/vite

      - name: Build
        run: npm run build
        working-directory: ./packages/vite

      - run: npm pkg-pr-new publish
        working-directory: ./packages/vite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
