name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        working-directory: ./packages/vite

      - name: Build
        run: pnpm build
        working-directory: ./packages/vite

      - name: Generate package tarball
        run: pnpm pack --dry-run | tail -n 1 | xargs tar -cf vite.tar

      - run: pnpm pkg-pr-new publish --tarball ./vite.tar
        working-directory: ./packages/vite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
