name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        working-directory: ./packages/vite

      - name: Build
        run: pnpm build
        working-directory: ./packages/vite

      - name: Override npm pack
        run: |
          chmod +x scripts/override-npm-pack.sh
          sudo mv scripts/override-npm-pack.sh /usr/local/bin/npm
        shell: bash

      - name: Publish
        run: pnpm pkg-pr-new publish
        working-directory: ./packages/vite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
