name: Publish Any Commit
on:
  push:
    branches:
      - main
      - v6/environment-api
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event_name == 'push' || github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - run: pnpx pkg-pr-new publish --pnpm ./packages/vite
